# Generated by Django 5.1.7 on 2025-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='mp_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
