# Generated by Django 5.1.7 on 2025-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plan_mp_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=20),
        ),
    ]
