# Generated by Django 5.1.7 on 2025-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='mp_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
