# Generated by Django 5.1.7 on 2025-07-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription_mp_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='frequency_type',
            field=models.CharField(default='months', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='repetitions',
            field=models.IntegerField(default=12),
        ),
    ]
