# Generated by Django 5.1.7 on 2025-07-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
